version: '3'
services:
  back:
    image: green_of_earth-back
    container_name: green_of_earth-back
    build: .
    ports:
      - "3008:3008" 
      - "3007:3007"
    restart: always

  front:
    image: green_of_earth-front
    container_name: green_of_earth-front
    build: .
    ports:
      - "80:8080" 
    restart: always